import type { Decade } from "@repo/utils"

export const decades: Decade[] = [
  {
    id: "1930s",
    label: "Los años 30",
    year: 1930,
    coverImage: "1930s/cover.webp",
    coverImageAlt: "Tomasa de niña en los años 30",
    slides: [
      {
        id: "1930s-1",
        type: "narrative",
        title: "El comienzo",
        text: "En un pequeño pueblo de México, nació una niña que cambiaría la vida de todos los que la conocieron. Tomasa llegó al mundo en una mañana de primavera, rodeada del aroma de tierra mojada y flores silvestres.",
      },
      {
        id: "1930s-2",
        type: "artwork",
        imageSrc: "1930s/drawing-01.webp",
        imageAlt: "Dibujo de la infancia de Tomasa",
        caption: "Recuerdos de la infancia",
      },
      {
        id: "1930s-3",
        type: "narrative",
        title: "La casa de adobe",
        text: "La casa donde creció tenía paredes de adobe y un patio lleno de macetas. Su mamá le enseñó a regar las plantas antes de que saliera el sol. Ahí aprendió que las cosas más hermosas requieren paciencia y cuidado.",
      },
      {
        id: "1930s-4",
        type: "artwork",
        imageSrc: "1930s/drawing-02.webp",
        imageAlt: "Dibujo del pueblo natal",
        caption: "El pueblo donde Tomasa creció",
      },
      {
        id: "1930s-5",
        type: "artwork",
        imageSrc: "1930s/drawing-03.webp",
        imageAlt: "Dibujo de la vida rural",
        caption: "Vida cotidiana en el pueblo",
      },
      {
        id: "1930s-6",
        type: "artwork",
        imageSrc: "1930s/drawing-04.webp",
        imageAlt: "Dibujo de la familia",
        caption: "Escenas familiares",
      },
      {
        id: "1930s-7",
        type: "artwork",
        imageSrc: "1930s/drawing-05.webp",
        imageAlt: "Dibujo de la naturaleza",
        caption: "La naturaleza del pueblo",
      },
      {
        id: "1930s-8",
        type: "artwork",
        imageSrc: "1930s/drawing-06.webp",
        imageAlt: "Dibujo de los primeros años",
        caption: "Los primeros años de Tomasa",
      },
    ],
  },
  {
    id: "1940s",
    label: "Los años 40",
    year: 1940,
    coverImage: "1940s/cover.webp",
    coverImageAlt: "Tomasa adolescente en los años 40",
    slides: [
      {
        id: "1940s-1",
        type: "narrative",
        title: "Juventud y esperanza",
        text: "Los años cuarenta trajeron cambios. Tomasa dejó la escuela para ayudar en casa, pero nunca dejó de aprender. Leía todo lo que encontraba y guardaba cuadernos llenos de recetas y remedios que le enseñaba su abuela.",
      },
      {
        id: "1940s-2",
        type: "artwork",
        imageSrc: "1940s/drawing-07.webp",
        imageAlt: "Dibujo de la juventud de Tomasa",
        caption: "La juventud de Tomasa",
      },
      {
        id: "1940s-3",
        type: "audio",
        title: "La voz de la memoria",
        text: "\"Mi abuela decía que cocinar es como rezar: hay que poner el corazón en cada paso.\"",
        audioSrc: "1940s/recuerdo.mp3",
        attribution: "Tomasa, recordando a su abuela materna",
      },
      {
        id: "1940s-4",
        type: "artwork",
        imageSrc: "1940s/drawing-08.webp",
        imageAlt: "Dibujo de la vida cotidiana",
        caption: "La vida cotidiana en los años 40",
      },
      {
        id: "1940s-5",
        type: "artwork",
        imageSrc: "1940s/drawing-09.webp",
        imageAlt: "Dibujo de los recuerdos",
        caption: "Recuerdos de juventud",
      },
      {
        id: "1940s-6",
        type: "artwork",
        imageSrc: "1940s/drawing-10.webp",
        imageAlt: "Dibujo de tradiciones",
        caption: "Tradiciones familiares",
      },
      {
        id: "1940s-7",
        type: "artwork",
        imageSrc: "1940s/drawing-11.webp",
        imageAlt: "Dibujo de aprendizaje",
        caption: "Aprendiendo de la abuela",
      },
      {
        id: "1940s-8",
        type: "artwork",
        imageSrc: "1940s/drawing-12.webp",
        imageAlt: "Dibujo de esperanza",
        caption: "Esperanza juvenil",
      },
    ],
  },
  {
    id: "1950s",
    label: "Los años 50",
    year: 1950,
    coverImage: "1950s/cover.webp",
    coverImageAlt: "Tomasa el día de su boda en los años 50",
    slides: [
      {
        id: "1950s-1",
        type: "narrative",
        title: "El amor llegó caminando",
        text: "Lo conoció en la fiesta del pueblo. Él le pidió un baile y ella le dijo que no. Al segundo baile, le dijo que sí. Así empezó una historia de amor que duraría toda la vida.",
      },
      {
        id: "1950s-2",
        type: "photo",
        imageSrc: "1950s/photo1.webp",
        imageAlt: "Tomasa joven, retrato en blanco y negro",
        caption: "Tomasa en 1951",
      },
      {
        id: "1950s-3",
        type: "photo",
        imageSrc: "1950s/photo2.webp",
        imageAlt: "Tomasa joven, segundo retrato",
        caption: "Tomasa en 1955",
      },
      {
        id: "1950s-4",
        type: "audio",
        title: "Canción de cuna",
        text: "\"Duérmete mi niño, duérmete mi sol, duérmete pedazo de mi corazón...\"",
        audioSrc: "1950s/cancion-cuna.mp3",
        attribution: "La canción que Tomasa les cantaba a todos sus hijos",
      },
      {
        id: "1950s-5",
        type: "narrative",
        title: "Un hogar nuevo",
        text: "Con mucho esfuerzo, Tomasa y su esposo construyeron su propia casa. Cada ladrillo representaba un sueño compartido. La cocina fue lo primero que terminaron, porque Tomasa decía que un hogar sin cocina no es hogar.",
      },
      {
        id: "1950s-6",
        type: "artwork",
        imageSrc: "1950s/drawing-13.webp",
        imageAlt: "Dibujo de la boda",
        caption: "Recuerdos de los años 50",
      },
      {
        id: "1950s-7",
        type: "artwork",
        imageSrc: "1950s/drawing-14.webp",
        imageAlt: "Dibujo del hogar",
        caption: "El nuevo hogar",
      },
      {
        id: "1950s-8",
        type: "artwork",
        imageSrc: "1950s/drawing-15.webp",
        imageAlt: "Dibujo de la familia joven",
        caption: "Los primeros años de familia",
      },
      {
        id: "1950s-9",
        type: "artwork",
        imageSrc: "1950s/drawing-16.webp",
        imageAlt: "Dibujo del amor",
        caption: "Historia de amor",
      },
      {
        id: "1950s-10",
        type: "artwork",
        imageSrc: "1950s/drawing-17.webp",
        imageAlt: "Dibujo de la cocina",
        caption: "La primera cocina",
      },
      {
        id: "1950s-11",
        type: "artwork",
        imageSrc: "1950s/drawing-18.webp",
        imageAlt: "Dibujo de sueños compartidos",
        caption: "Sueños compartidos",
      },
    ],
  },
  {
    id: "1960s",
    label: "Los años 60",
    year: 1960,
    coverImage: "1960s/cover.webp",
    coverImageAlt: "Tomasa rodeada de sus hijos en los años 60",
    slides: [
      {
        id: "1960s-1",
        type: "narrative",
        title: "La mesa siempre llena",
        text: "Para los años sesenta, la familia había crecido. Seis hijos llenaban la casa de risas, travesuras y hambre. Tomasa cocinaba ollas enormes de frijoles, arroz y guisados que alcanzaban para todos — y siempre sobraba para el vecino.",
      },
      {
        id: "1960s-2",
        type: "artwork",
        imageSrc: "1960s/drawing-19.webp",
        imageAlt: "Dibujo de la familia numerosa",
        caption: "La familia crecía",
      },
      {
        id: "1960s-3",
        type: "audio",
        title: "Sabiduría de cocina",
        text: "\"El secreto del mole no está en los ingredientes, está en la paciencia. Hay que mover y mover sin parar, como la vida misma.\"",
        audioSrc: "1960s/mole.mp3",
        attribution: "Tomasa, explicando su receta familiar",
      },
      {
        id: "1960s-4",
        type: "artwork",
        imageSrc: "1960s/drawing-20.webp",
        imageAlt: "Dibujo de la cocina familiar",
        caption: "La cocina de Tomasa",
      },
      {
        id: "1960s-5",
        type: "artwork",
        imageSrc: "1960s/drawing-21.webp",
        imageAlt: "Dibujo de los hijos",
        caption: "Los hijos de Tomasa",
      },
      {
        id: "1960s-6",
        type: "artwork",
        imageSrc: "1960s/drawing-22.webp",
        imageAlt: "Dibujo de la mesa familiar",
        caption: "La mesa siempre llena",
      },
      {
        id: "1960s-7",
        type: "artwork",
        imageSrc: "1960s/drawing-23.webp",
        imageAlt: "Dibujo de tradiciones culinarias",
        caption: "Tradiciones culinarias",
      },
      {
        id: "1960s-8",
        type: "artwork",
        imageSrc: "1960s/drawing-24.webp",
        imageAlt: "Dibujo de la vida en los 60",
        caption: "La vida en los años 60",
      },
    ],
  },
  {
    id: "1970s",
    label: "Los años 70",
    year: 1970,
    coverImage: "1970s/cover.webp",
    coverImageAlt: "Tomasa en los años 70",
    slides: [
      {
        id: "1970s-1",
        type: "narrative",
        title: "Raíces y alas",
        text: "Los hijos empezaron a irse. Uno a la ciudad, otra al norte. Tomasa los despedía con bolsas llenas de comida y los ojos llenos de lágrimas que nunca dejaba ver. Les repetía siempre: \"Llévense sus raíces adonde vayan.\"",
      },
      {
        id: "1970s-2",
        type: "photo",
        imageSrc: "1970s/photo1.webp",
        imageAlt: "Tomasa en los años 70, retrato a color",
        caption: "Tomasa en 1975",
      },
      {
        id: "1970s-3",
        type: "narrative",
        title: "Abuela por primera vez",
        text: "Cuando nació el primer nieto, Tomasa dijo que entendió por fin lo que significaba el amor sin condiciones. Desde ese día, su delantal siempre tenía dulces escondidos en los bolsillos.",
      },
      {
        id: "1970s-4",
        type: "artwork",
        imageSrc: "1970s/drawing-25.webp",
        imageAlt: "Dibujo de la despedida",
        caption: "Despedidas y nuevos comienzos",
      },
      {
        id: "1970s-5",
        type: "artwork",
        imageSrc: "1970s/drawing-26.webp",
        imageAlt: "Dibujo de los nietos",
        caption: "Los primeros nietos",
      },
      {
        id: "1970s-6",
        type: "artwork",
        imageSrc: "1970s/drawing-27.webp",
        imageAlt: "Dibujo de raíces",
        caption: "Raíces profundas",
      },
      {
        id: "1970s-7",
        type: "artwork",
        imageSrc: "1970s/drawing-28.webp",
        imageAlt: "Dibujo de la familia extendida",
        caption: "La familia crece",
      },
      {
        id: "1970s-8",
        type: "artwork",
        imageSrc: "1970s/drawing-29.webp",
        imageAlt: "Dibujo del amor de abuela",
        caption: "Amor de abuela",
      },
      {
        id: "1970s-9",
        type: "artwork",
        imageSrc: "1970s/drawing-30.webp",
        imageAlt: "Dibujo de los años 70",
        caption: "Recuerdos de los años 70",
      },
    ],
  },
  {
    id: "1980s",
    label: "Los años 80",
    year: 1980,
    coverImage: "1980s/cover.webp",
    coverImageAlt: "Tomasa rodeada de nietos en los años 80",
    slides: [
      {
        id: "1980s-1",
        type: "narrative",
        title: "La abuela de todos",
        text: "En los ochenta, la casa de Tomasa se convirtió en el centro del universo familiar. Cada domingo, cada cumpleaños, cada Navidad — todo pasaba en su cocina. Los nietos corrían por el patio mientras ella preparaba tamales.",
      },
      {
        id: "1980s-2",
        type: "photo",
        imageSrc: "1980s/photo1.webp",
        imageAlt: "Tomasa con su familia en los años 80",
        caption: "Tomasa en 1980",
      },
      {
        id: "1980s-3",
        type: "photo",
        imageSrc: "1980s/photo2.webp",
        imageAlt: "Tomasa con la familia, 1984",
        caption: "Reunión familiar, 1984",
      },
      {
        id: "1980s-4",
        type: "audio",
        title: "Consejo eterno",
        text: "\"Mijo, en esta vida lo único que te llevas es lo que diste. Así que da mucho — da comida, da cariño, da tu tiempo.\"",
        audioSrc: "1980s/consejo.mp3",
        attribution: "Tomasa, hablando con sus nietos",
      },
      {
        id: "1980s-5",
        type: "narrative",
        title: "Lo que permanece",
        text: "Tomasa nunca buscó ser recordada. Simplemente vivió con el corazón abierto, las manos siempre ocupadas y la puerta siempre abierta. Su legado no está en monumentos sino en cada plato que cocinamos con su receta, en cada abrazo que damos sin razón.",
      },
      {
        id: "1980s-6",
        type: "artwork",
        imageSrc: "1980s/drawing-31.webp",
        imageAlt: "Dibujo de la Navidad",
        caption: "Navidades en familia",
      },
      {
        id: "1980s-7",
        type: "artwork",
        imageSrc: "1980s/drawing-32.webp",
        imageAlt: "Dibujo de los tamales",
        caption: "Haciendo tamales",
      },
      {
        id: "1980s-8",
        type: "artwork",
        imageSrc: "1980s/drawing-33.webp",
        imageAlt: "Dibujo del patio",
        caption: "El patio de la abuela",
      },
      {
        id: "1980s-9",
        type: "artwork",
        imageSrc: "1980s/drawing-34.webp",
        imageAlt: "Dibujo de reunión familiar",
        caption: "Domingos en familia",
      },
      {
        id: "1980s-10",
        type: "artwork",
        imageSrc: "1980s/drawing-35.webp",
        imageAlt: "Dibujo del legado",
        caption: "El legado de Tomasa",
      },
      {
        id: "1980s-11",
        type: "artwork",
        imageSrc: "1980s/drawing-36.webp",
        imageAlt: "Dibujo de los años 80",
        caption: "Recuerdos de los años 80",
      },
    ],
  },
  {
    id: "1990s",
    label: "Los años 90",
    year: 1990,
    coverImage: "1990s/cover.webp",
    coverImageAlt: "Tomasa en los años 90",
    slides: [
      {
        id: "1990s-1",
        type: "narrative",
        title: "Sabiduría tranquila",
        text: "Los noventa encontraron a Tomasa más serena pero igual de fuerte. Su casa seguía siendo el punto de reunión, el lugar donde todos regresaban. Los nietos ya traían a sus propias parejas a conocer a la abuela.",
      },
      {
        id: "1990s-2",
        type: "photo",
        imageSrc: "1990s/photo1.webp",
        imageAlt: "Tomasa en los años 90, retrato a color",
        caption: "Tomasa en 1990",
      },
      {
        id: "1990s-3",
        type: "photo",
        imageSrc: "1990s/photo2.webp",
        imageAlt: "Tomasa en los años 90",
        caption: "Tomasa en 1997",
      },
      {
        id: "1990s-4",
        type: "narrative",
        title: "El jardín de la abuela",
        text: "Su jardín se convirtió en su orgullo. Rosas, jazmines y hierbas medicinales crecían bajo su cuidado. Decía que las plantas son como los hijos: cada una necesita algo diferente, pero todas necesitan amor.",
      },
      {
        id: "1990s-5",
        type: "artwork",
        imageSrc: "1990s/drawing-37.webp",
        imageAlt: "Dibujo del jardín",
        caption: "El jardín de Tomasa",
      },
      {
        id: "1990s-6",
        type: "artwork",
        imageSrc: "1990s/drawing-38.webp",
        imageAlt: "Dibujo de sabiduría",
        caption: "Sabiduría de los años",
      },
      {
        id: "1990s-7",
        type: "artwork",
        imageSrc: "1990s/drawing-39.webp",
        imageAlt: "Dibujo de reuniones",
        caption: "Reuniones familiares",
      },
      {
        id: "1990s-8",
        type: "artwork",
        imageSrc: "1990s/drawing-40.webp",
        imageAlt: "Dibujo de tradiciones",
        caption: "Tradiciones que perduran",
      },
      {
        id: "1990s-9",
        type: "artwork",
        imageSrc: "1990s/drawing-41.webp",
        imageAlt: "Dibujo de los años 90",
        caption: "Recuerdos de los años 90",
      },
    ],
  },
  {
    id: "2000s",
    label: "Los años 2000",
    year: 2000,
    coverImage: "2000s/cover.webp",
    coverImageAlt: "Tomasa en los años 2000",
    slides: [
      {
        id: "2000s-1",
        type: "narrative",
        title: "Un nuevo siglo",
        text: "El mundo cambió, pero Tomasa seguía igual. Su cocina no tenía microondas ni necesitaba uno. Sus recetas no estaban en internet sino en su memoria. Los bisnietos la miraban con asombro, como quien descubre un tesoro antiguo.",
      },
      {
        id: "2000s-2",
        type: "photo",
        imageSrc: "2000s/photo1.webp",
        imageAlt: "Tomasa en el año 2000",
        caption: "Tomasa en el nuevo milenio, 2000",
      },
      {
        id: "2000s-3",
        type: "photo",
        imageSrc: "2000s/photo2.webp",
        imageAlt: "Tomasa sentada, 2001",
        caption: "Tomasa en 2001",
      },
      {
        id: "2000s-4",
        type: "photo",
        imageSrc: "2000s/photo3.webp",
        imageAlt: "Tomasa, retrato en azul",
        caption: "Tomasa en 2008",
      },
      {
        id: "2000s-5",
        type: "narrative",
        title: "Cuatro generaciones",
        text: "Tomasa vivió para ver cuatro generaciones de su familia. En las fotos familiares, ella siempre estaba en el centro, pequeña pero imponente, con esa sonrisa que iluminaba cualquier cuarto.",
      },
      {
        id: "2000s-6",
        type: "artwork",
        imageSrc: "2000s/drawing-42.webp",
        imageAlt: "Dibujo del nuevo siglo",
        caption: "Un nuevo siglo",
      },
      {
        id: "2000s-7",
        type: "artwork",
        imageSrc: "2000s/drawing-43.webp",
        imageAlt: "Dibujo de generaciones",
        caption: "Cuatro generaciones",
      },
      {
        id: "2000s-8",
        type: "artwork",
        imageSrc: "2000s/drawing-44.webp",
        imageAlt: "Dibujo de la cocina eterna",
        caption: "La cocina eterna",
      },
      {
        id: "2000s-9",
        type: "artwork",
        imageSrc: "2000s/drawing-45.webp",
        imageAlt: "Dibujo de bisnietos",
        caption: "Los bisnietos de Tomasa",
      },
      {
        id: "2000s-10",
        type: "artwork",
        imageSrc: "2000s/drawing-46.webp",
        imageAlt: "Dibujo de los años 2000",
        caption: "Recuerdos de los años 2000",
      },
    ],
  },
  {
    id: "2010s",
    label: "Los años 2010",
    year: 2010,
    coverImage: "2010s/cover.webp",
    coverImageAlt: "Tomasa en los años 2010",
    slides: [
      {
        id: "2010s-1",
        type: "narrative",
        title: "La luz que no se apaga",
        text: "En sus últimos años, Tomasa seguía levantándose temprano, preparando café y esperando a que alguien tocara la puerta. Su memoria ya no era la misma, pero nunca olvidó una receta ni el nombre de un nieto.",
      },
      {
        id: "2010s-2",
        type: "photo",
        imageSrc: "2010s/photo1.webp",
        imageAlt: "Tomasa en 2013",
        caption: "Tomasa en 2013",
      },
      {
        id: "2010s-3",
        type: "narrative",
        title: "Siempre presente",
        text: "Tomasa nos enseñó que el amor se demuestra con hechos pequeños: un plato de comida, una manta cuando hace frío, un abrazo sin preguntar por qué. Su presencia llenaba cualquier espacio, y su ausencia dejó un vacío que sólo se llena recordándola.",
      },
      {
        id: "2010s-4",
        type: "artwork",
        imageSrc: "2010s/drawing-47.webp",
        imageAlt: "Dibujo de los últimos años",
        caption: "La luz que no se apaga",
      },
      {
        id: "2010s-5",
        type: "artwork",
        imageSrc: "2010s/drawing-48.webp",
        imageAlt: "Dibujo de recuerdos",
        caption: "Recuerdos eternos",
      },
      {
        id: "2010s-6",
        type: "artwork",
        imageSrc: "2010s/drawing-49.webp",
        imageAlt: "Dibujo del legado",
        caption: "El legado vive",
      },
      {
        id: "2010s-7",
        type: "artwork",
        imageSrc: "2010s/drawing-50.webp",
        imageAlt: "Dibujo de gratitud",
        caption: "Gratitud eterna",
      },
      {
        id: "2010s-8",
        type: "artwork",
        imageSrc: "2010s/drawing-51.webp",
        imageAlt: "Dibujo de amor eterno",
        caption: "Siempre en nuestro corazón",
      },
    ],
  },
]
