import type { Decade } from "@repo/utils"

export const decades: Decade[] = [
  {
    id: "1930s",
    label: "Los años 30",
    year: 1930,
    coverImage: "1930s/cover.webp",
    coverImageAlt: "Tomasa de niña en los años 30",
    slides: [
      {
        id: "1930s-1",
        type: "narrative",
        title: "La vida en el rancho",
        text: "Nosotros en el rancho, hiciera frío, hiciera calor, lo que fuera. Nosotros andamos descalzos sin suéter. Pero fíjate que éramos tan felices, que no sentíamos nada.",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1930s-2",
        type: "artwork",
        imageSrc: "1930s/drawing-01.webp",
        imageAlt: "Dibujo de la infancia de Tomasa",
        caption: "Recuerdos de la infancia",
      },
      {
        id: "1930s-audio-1",
        type: "audio",
        title: "Felices sin tener nada",
        text: "\"Nosotros en el rancho, si era frío, si era calor, lo que fuera. Nosotros andábamos descalzos, sin suéter. Pero fíjate que éramos tan felices, que no sentíamos nada.\"",
        audioSrc: "1930s/rancho.mp3",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1930s-3",
        type: "narrative",
        title: "El rancho El Oro",
        text: "A los Ulices yo volví cuando tenía como cinco años, porque mi papá se fue al rancho. Tenía unas tierras y animales. No había escuelas, veníamos muy cerrados del rancho. Era todo muy pacífico, muy tranquilo.",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1930s-4",
        type: "artwork",
        imageSrc: "1930s/drawing-02.webp",
        imageAlt: "Dibujo del pueblo natal",
        caption: "El pueblo donde Tomasa creció",
      },
      {
        id: "1930s-5",
        type: "artwork",
        imageSrc: "1930s/drawing-03.webp",
        imageAlt: "Dibujo de la vida rural",
        caption: "Vida cotidiana en el pueblo",
      },
      {
        id: "1930s-6",
        type: "artwork",
        imageSrc: "1930s/drawing-04.webp",
        imageAlt: "Dibujo de la familia",
        caption: "Escenas familiares",
      },
      {
        id: "1930s-7",
        type: "artwork",
        imageSrc: "1930s/drawing-05.webp",
        imageAlt: "Dibujo de la naturaleza",
        caption: "La naturaleza del pueblo",
      },
      {
        id: "1930s-8",
        type: "artwork",
        imageSrc: "1930s/drawing-06.webp",
        imageAlt: "Dibujo de los primeros años",
        caption: "Los primeros años de Tomasa",
      },
    ],
  },
  {
    id: "1940s",
    label: "Los años 40",
    year: 1940,
    coverImage: "1940s/cover.webp",
    coverImageAlt: "Tomasa adolescente en los años 40",
    slides: [
      {
        id: "1940s-1",
        type: "narrative",
        title: "A trabajar desde los quince",
        text: "Yo me vine a Chihuahua. Aquí se vino Evaristo primero, con mi papá, que lo pusieron en el centro de salud, porque mi papá como perdió un ojo. Y me puse a trabajar aquí, cuidando niños. Como veníamos del rancho, muy cerrados, sin escuelas.",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1940s-2",
        type: "artwork",
        imageSrc: "1940s/drawing-07.webp",
        imageAlt: "Dibujo de la juventud de Tomasa",
        caption: "La juventud de Tomasa",
      },
      {
        id: "1940s-3",
        type: "audio",
        title: "Aprendiendo a cocinar",
        text: "\"Yo trabajé nomás en casas de los ricos, en cocina, y aprendí a hacer comida. Porque antes no sabíamos nada. En el rancho, a veces mi papá llevaba una sandía — era lo que comíamos un día o dos.\"",
        audioSrc: "1940s/recuerdo.mp3",
        attribution: "Tomasa, entrevistas domingo 17:04 y domingo 22:08",
      },
      {
        id: "1940s-4",
        type: "artwork",
        imageSrc: "1940s/drawing-08.webp",
        imageAlt: "Dibujo de la vida cotidiana",
        caption: "La vida cotidiana en los años 40",
      },
      {
        id: "1940s-5",
        type: "artwork",
        imageSrc: "1940s/drawing-09.webp",
        imageAlt: "Dibujo de los recuerdos",
        caption: "Recuerdos de juventud",
      },
      {
        id: "1940s-6",
        type: "artwork",
        imageSrc: "1940s/drawing-10.webp",
        imageAlt: "Dibujo de tradiciones",
        caption: "Tradiciones familiares",
      },
      {
        id: "1940s-7",
        type: "artwork",
        imageSrc: "1940s/drawing-11.webp",
        imageAlt: "Dibujo de aprendizaje",
        caption: "Aprendiendo de la abuela",
      },
      {
        id: "1940s-8",
        type: "artwork",
        imageSrc: "1940s/drawing-12.webp",
        imageAlt: "Dibujo de esperanza",
        caption: "Esperanza juvenil",
      },
    ],
  },
  {
    id: "1950s",
    label: "Los años 50",
    year: 1950,
    coverImage: "1950s/cover.webp",
    coverImageAlt: "Tomasa el día de su boda en los años 50",
    slides: [
      {
        id: "1950s-1",
        type: "narrative",
        title: "El novio de Parral",
        text: "Yo me junté con mi novio en Parral. Él era de Durango y se fue a trabajar allá. Yo tenía como 23 años cuando tuve a mi hijo. Y después se murió el papá de mi hijo — le dieron un balazo en el espinazo y se murió.",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1950s-2",
        type: "photo",
        imageSrc: "1950s/photo1.webp",
        imageAlt: "Tomasa joven, retrato en blanco y negro",
        caption: "Tomasa en 1951",
      },
      {
        id: "1950s-3",
        type: "photo",
        imageSrc: "1950s/photo2.webp",
        imageAlt: "Tomasa joven, segundo retrato",
        caption: "Tomasa en 1955",
      },
      {
        id: "1950s-4",
        type: "audio",
        title: "La familia crece",
        text: "\"Luego tuve a mi hijo, luego tuve a otro. Todos nos fuimos a la sierra. Allí empezaron a crecer todos mis muchachitos. No había escuela, no había nada — había una escuela radiofónica, por radio.\"",
        audioSrc: "1950s/cancion-cuna.mp3",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1950s-5",
        type: "narrative",
        title: "Seguir adelante",
        text: "Entonces ya duró en la cama y ya se murió. Y ya me fui con mi cuñada, porque ya no tenía mamá. Me fui con mi cuñada para que me cuidara mi hijo, para yo poder trabajar. Y ya después de allí me vine a Chihuahua.",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1950s-6",
        type: "artwork",
        imageSrc: "1950s/drawing-13.webp",
        imageAlt: "Dibujo de la boda",
        caption: "Recuerdos de los años 50",
      },
      {
        id: "1950s-7",
        type: "artwork",
        imageSrc: "1950s/drawing-14.webp",
        imageAlt: "Dibujo del hogar",
        caption: "El nuevo hogar",
      },
      {
        id: "1950s-8",
        type: "artwork",
        imageSrc: "1950s/drawing-15.webp",
        imageAlt: "Dibujo de la familia joven",
        caption: "Los primeros años de familia",
      },
      {
        id: "1950s-9",
        type: "artwork",
        imageSrc: "1950s/drawing-16.webp",
        imageAlt: "Dibujo del amor",
        caption: "Historia de amor",
      },
      {
        id: "1950s-10",
        type: "artwork",
        imageSrc: "1950s/drawing-17.webp",
        imageAlt: "Dibujo de la cocina",
        caption: "La primera cocina",
      },
      {
        id: "1950s-11",
        type: "artwork",
        imageSrc: "1950s/drawing-18.webp",
        imageAlt: "Dibujo de sueños compartidos",
        caption: "Sueños compartidos",
      },
    ],
  },
  {
    id: "1960s",
    label: "Los años 60",
    year: 1960,
    coverImage: "1960s/cover.webp",
    coverImageAlt: "Tomasa rodeada de sus hijos en los años 60",
    slides: [
      {
        id: "1960s-1",
        type: "narrative",
        title: "La sierra y la madera",
        text: "Le dieron trabajo a mi señor en una fábrica de madera. Allí empezaron a crecer todos mis muchachitos. Subíamos como cuarenta escalones a donde estaba la casa de madera. Ahí vivimos algún tiempo.",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1960s-2",
        type: "artwork",
        imageSrc: "1960s/drawing-19.webp",
        imageAlt: "Dibujo de la familia numerosa",
        caption: "La familia crecía",
      },
      {
        id: "1960s-3",
        type: "audio",
        title: "Las enchiladas de Parral",
        text: "\"Yo me ayudaba. Molíamos chile. Así es cuando hacíamos las tortillas. Hacíamos enchiladas muy buenas. Había gente que compraba. Quién sabe ahora cómo chata.\"",
        audioSrc: "1960s/mole.mp3",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1960s-4",
        type: "artwork",
        imageSrc: "1960s/drawing-20.webp",
        imageAlt: "Dibujo de la cocina familiar",
        caption: "La cocina de Tomasa",
      },
      {
        id: "1960s-5",
        type: "artwork",
        imageSrc: "1960s/drawing-21.webp",
        imageAlt: "Dibujo de los hijos",
        caption: "Los hijos de Tomasa",
      },
      {
        id: "1960s-6",
        type: "artwork",
        imageSrc: "1960s/drawing-22.webp",
        imageAlt: "Dibujo de la mesa familiar",
        caption: "La mesa siempre llena",
      },
      {
        id: "1960s-7",
        type: "artwork",
        imageSrc: "1960s/drawing-23.webp",
        imageAlt: "Dibujo de tradiciones culinarias",
        caption: "Tradiciones culinarias",
      },
      {
        id: "1960s-8",
        type: "artwork",
        imageSrc: "1960s/drawing-24.webp",
        imageAlt: "Dibujo de la vida en los 60",
        caption: "La vida en los años 60",
      },
    ],
  },
  {
    id: "1970s",
    label: "Los años 70",
    year: 1970,
    coverImage: "1970s/cover.webp",
    coverImageAlt: "Tomasa en los años 70",
    slides: [
      {
        id: "1970s-1",
        type: "narrative",
        title: "El hombre en la luna",
        text: "Cuando llegó el hombre a la luna, lo vimos. Estábamos en Buchiniva. Lo vimos en una tele chiquita, como a doscientos metros de donde estábamos. Yo ya tenía mis años. Y los niños todos querían ir a ver eso.",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1970s-2",
        type: "photo",
        imageSrc: "1970s/photo1.webp",
        imageAlt: "Tomasa en los años 70, retrato a color",
        caption: "Tomasa en 1975",
      },
      {
        id: "1970s-3",
        type: "narrative",
        title: "Los nietos y el cariño",
        text: "Y luego los nietos también me cuidan. Todos me quieren. Aquí me la paso muy bien con los niños. Los niños van a la escuela pero cuando vienen — ellos aquí se la pasan muy bien.",
        attribution: "Tomasa, entrevistas domingo 17:04 y miércoles 17:57",
      },
      {
        id: "1970s-audio-1",
        type: "audio",
        title: "El hombre en la luna",
        text: "\"Cuando llegó el hombre a la luna, lo vimos en Guichivo. Lo vimos en una tele chiquita, como a doscientos metros de donde estábamos. Y los niños todos querían ir a ver eso.\"",
        audioSrc: "1970s/luna.mp3",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1970s-4",
        type: "artwork",
        imageSrc: "1970s/drawing-25.webp",
        imageAlt: "Dibujo de la despedida",
        caption: "Despedidas y nuevos comienzos",
      },
      {
        id: "1970s-5",
        type: "artwork",
        imageSrc: "1970s/drawing-26.webp",
        imageAlt: "Dibujo de los nietos",
        caption: "Los primeros nietos",
      },
      {
        id: "1970s-6",
        type: "artwork",
        imageSrc: "1970s/drawing-27.webp",
        imageAlt: "Dibujo de raíces",
        caption: "Raíces profundas",
      },
      {
        id: "1970s-7",
        type: "artwork",
        imageSrc: "1970s/drawing-28.webp",
        imageAlt: "Dibujo de la familia extendida",
        caption: "La familia crece",
      },
      {
        id: "1970s-8",
        type: "artwork",
        imageSrc: "1970s/drawing-29.webp",
        imageAlt: "Dibujo del amor de abuela",
        caption: "Amor de abuela",
      },
      {
        id: "1970s-9",
        type: "artwork",
        imageSrc: "1970s/drawing-30.webp",
        imageAlt: "Dibujo de los años 70",
        caption: "Recuerdos de los años 70",
      },
    ],
  },
  {
    id: "1980s",
    label: "Los años 80",
    year: 1980,
    coverImage: "1980s/cover.webp",
    coverImageAlt: "Tomasa rodeada de nietos en los años 80",
    slides: [
      {
        id: "1980s-1",
        type: "narrative",
        title: "Jugando con los nietos",
        text: "Antes tenía uno que jugar con ellos más. Antes tenía uno que entenderles más. ¿Usted qué hacía? Pues jugábamos con un juguete que traía. ¿Usted jugaba con ellos? Sí — antes pues tenía uno que entenderles lo más.",
        attribution: "Tomasa, entrevista miércoles 17:57",
      },
      {
        id: "1980s-2",
        type: "photo",
        imageSrc: "1980s/photo1.webp",
        imageAlt: "Tomasa con su familia en los años 80",
        caption: "Tomasa en 1980",
      },
      {
        id: "1980s-3",
        type: "photo",
        imageSrc: "1980s/photo2.webp",
        imageAlt: "Tomasa con la familia, 1984",
        caption: "Reunión familiar, 1984",
      },
      {
        id: "1980s-4",
        type: "audio",
        title: "La felicidad sin tener nada",
        text: "\"No teníamos miedo, no. Era todo muy pacífico, muy tranquilo. Y fíjate que éramos tan felices. Vamos felices de todos modos, mi hijo.\"",
        audioSrc: "1980s/consejo.mp3",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1980s-5",
        type: "narrative",
        title: "La Navidad antes",
        text: "Antes no le conocíamos la Navidad. Este cuando yo estaba muy grande ya. Y por ejemplo, ¿cómo estabas? ¿Les dabas regalos? Sí. ¿Cómo se sintió cuando ya les daban regalos? Pues muy bien.",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1980s-6",
        type: "artwork",
        imageSrc: "1980s/drawing-31.webp",
        imageAlt: "Dibujo de la Navidad",
        caption: "Navidades en familia",
      },
      {
        id: "1980s-7",
        type: "artwork",
        imageSrc: "1980s/drawing-32.webp",
        imageAlt: "Dibujo de los tamales",
        caption: "Haciendo tamales",
      },
      {
        id: "1980s-8",
        type: "artwork",
        imageSrc: "1980s/drawing-33.webp",
        imageAlt: "Dibujo del patio",
        caption: "El patio de la abuela",
      },
      {
        id: "1980s-9",
        type: "artwork",
        imageSrc: "1980s/drawing-34.webp",
        imageAlt: "Dibujo de reunión familiar",
        caption: "Domingos en familia",
      },
      {
        id: "1980s-10",
        type: "artwork",
        imageSrc: "1980s/drawing-35.webp",
        imageAlt: "Dibujo del legado",
        caption: "El legado de Tomasa",
      },
      {
        id: "1980s-11",
        type: "artwork",
        imageSrc: "1980s/drawing-36.webp",
        imageAlt: "Dibujo de los años 80",
        caption: "Recuerdos de los años 80",
      },
    ],
  },
  {
    id: "1990s",
    label: "Los años 90",
    year: 1990,
    coverImage: "1990s/cover.webp",
    coverImageAlt: "Tomasa en los años 90",
    slides: [
      {
        id: "1990s-1",
        type: "narrative",
        title: "Los hijos que se van",
        text: "No me sentía muy bien cuando se fue. Si no sabía para dónde se había ido hasta que no le habló a mi guía, que trabajaba en una farmacia. Y le dijo que estaba en Monterrey.",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "1990s-2",
        type: "photo",
        imageSrc: "1990s/photo1.webp",
        imageAlt: "Tomasa en los años 90, retrato a color",
        caption: "Tomasa en 1990",
      },
      {
        id: "1990s-3",
        type: "photo",
        imageSrc: "1990s/photo2.webp",
        imageAlt: "Tomasa en los años 90",
        caption: "Tomasa en 1997",
      },
      {
        id: "1990s-4",
        type: "narrative",
        title: "Las flores y los dibujos",
        text: "Aquí tengo los pinos. Ahí las mariposas volando y los patos en el lago — pues me las imagino. Las flores en el jardín, pues yo las flores me gustan mucho.",
        attribution: "Tomasa, noviembre 2024",
      },
      {
        id: "1990s-5",
        type: "artwork",
        imageSrc: "1990s/drawing-37.webp",
        imageAlt: "Dibujo del jardín",
        caption: "El jardín de Tomasa",
      },
      {
        id: "1990s-6",
        type: "artwork",
        imageSrc: "1990s/drawing-38.webp",
        imageAlt: "Dibujo de sabiduría",
        caption: "Sabiduría de los años",
      },
      {
        id: "1990s-7",
        type: "artwork",
        imageSrc: "1990s/drawing-39.webp",
        imageAlt: "Dibujo de reuniones",
        caption: "Reuniones familiares",
      },
      {
        id: "1990s-8",
        type: "artwork",
        imageSrc: "1990s/drawing-40.webp",
        imageAlt: "Dibujo de tradiciones",
        caption: "Tradiciones que perduran",
      },
      {
        id: "1990s-9",
        type: "artwork",
        imageSrc: "1990s/drawing-41.webp",
        imageAlt: "Dibujo de los años 90",
        caption: "Recuerdos de los años 90",
      },
    ],
  },
  {
    id: "2000s",
    label: "Los años 2000",
    year: 2000,
    coverImage: "2000s/cover.webp",
    coverImageAlt: "Tomasa en los años 2000",
    slides: [
      {
        id: "2000s-1",
        type: "narrative",
        title: "Pensar y hacer",
        text: "Estaba pensando en él. Yo creo que todos los días pienso, porque tengo esas cosas que hago cuando no tengo nada que hacer. Me pongo a dibujar — unos claveles, margaritas, pinos.",
        attribution: "Tomasa, noviembre 2024",
      },
      {
        id: "2000s-2",
        type: "photo",
        imageSrc: "2000s/photo1.webp",
        imageAlt: "Tomasa en el año 2000",
        caption: "Tomasa en el nuevo milenio, 2000",
      },
      {
        id: "2000s-3",
        type: "photo",
        imageSrc: "2000s/photo2.webp",
        imageAlt: "Tomasa sentada, 2001",
        caption: "Tomasa en 2001",
      },
      {
        id: "2000s-4",
        type: "photo",
        imageSrc: "2000s/photo3.webp",
        imageAlt: "Tomasa, retrato en azul",
        caption: "Tomasa en 2008",
      },
      {
        id: "2000s-5",
        type: "narrative",
        title: "Las criaturas que cuidan",
        text: "Las criaturas, todos los nietos. Y luego los nietos también me cuidan. Todos me quieren. Sí, y todos me quieren, todos me cuidan.",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "2000s-6",
        type: "artwork",
        imageSrc: "2000s/drawing-42.webp",
        imageAlt: "Dibujo del nuevo siglo",
        caption: "Un nuevo siglo",
      },
      {
        id: "2000s-7",
        type: "artwork",
        imageSrc: "2000s/drawing-43.webp",
        imageAlt: "Dibujo de generaciones",
        caption: "Cuatro generaciones",
      },
      {
        id: "2000s-8",
        type: "artwork",
        imageSrc: "2000s/drawing-44.webp",
        imageAlt: "Dibujo de la cocina eterna",
        caption: "La cocina eterna",
      },
      {
        id: "2000s-9",
        type: "artwork",
        imageSrc: "2000s/drawing-45.webp",
        imageAlt: "Dibujo de bisnietos",
        caption: "Los bisnietos de Tomasa",
      },
      {
        id: "2000s-10",
        type: "artwork",
        imageSrc: "2000s/drawing-46.webp",
        imageAlt: "Dibujo de los años 2000",
        caption: "Recuerdos de los años 2000",
      },
    ],
  },
  {
    id: "2010s",
    label: "Los años 2010",
    year: 2010,
    coverImage: "2010s/cover.webp",
    coverImageAlt: "Tomasa en los años 2010",
    slides: [
      {
        id: "2010s-1",
        type: "narrative",
        title: "Ahí la llevo",
        text: "De un brazo, de los riñones, de la presión, y luego me están dando terapia en el brazo. Porque no lo muevo muy bien. Ahí la llevo, ahí la llevo. Pero estoy bien.",
        attribution: "Tomasa, entrevista miércoles 17:57",
      },
      {
        id: "2010s-2",
        type: "photo",
        imageSrc: "2010s/photo1.webp",
        imageAlt: "Tomasa en 2013",
        caption: "Tomasa en 2013",
      },
      {
        id: "2010s-3",
        type: "narrative",
        title: "Estoy bien",
        text: "Pero no me caí, nada, nada. Yo estoy bien. ¿Tú cómo estás? Pues qué bueno, mi hijo, mientras tengas trabajo. Trabaje y trabaje, ¿no?",
        attribution: "Tomasa, entrevista domingo 17:04",
      },
      {
        id: "2010s-audio-1",
        type: "audio",
        title: "Ahí la llevo",
        text: "\"Me están dando terapia en el brazo, porque no lo muevo muy bien. Pero sí puedo hacer cosas con la mano izquierda, sí. Ahí la llevo. Pero yo estoy bien.\"",
        audioSrc: "2010s/brazo.mp3",
        attribution: "Tomasa, entrevista miércoles 17:57",
      },
      {
        id: "2010s-4",
        type: "artwork",
        imageSrc: "2010s/drawing-47.webp",
        imageAlt: "Dibujo de los últimos años",
        caption: "La luz que no se apaga",
      },
      {
        id: "2010s-5",
        type: "artwork",
        imageSrc: "2010s/drawing-48.webp",
        imageAlt: "Dibujo de recuerdos",
        caption: "Recuerdos eternos",
      },
      {
        id: "2010s-6",
        type: "artwork",
        imageSrc: "2010s/drawing-49.webp",
        imageAlt: "Dibujo del legado",
        caption: "El legado vive",
      },
      {
        id: "2010s-7",
        type: "artwork",
        imageSrc: "2010s/drawing-50.webp",
        imageAlt: "Dibujo de gratitud",
        caption: "Gratitud eterna",
      },
      {
        id: "2010s-8",
        type: "artwork",
        imageSrc: "2010s/drawing-51.webp",
        imageAlt: "Dibujo de amor eterno",
        caption: "Siempre en nuestro corazón",
      },
    ],
  },
]
